import atacama from "./viagens/atacama.png";
import veneza from "./viagens/veneza.png";
import patagonia from "./viagens/patagonia.png";
import grandCanyon from "./viagens/grandCanyon.png";
import turquia from "./viagens/turquia.png";
import cordilheiraDosAndes from "./viagens/cordilheiraDosAndes.png";
import novaYork from "./viagens/novaYork.png";
import bonito from "./viagens/bonito.png";
import toronto from "./viagens/toronto.png";
import viena from "./viagens/viena.png";
import salvador from "./viagens/salvador.png";
import arraialDoCabo from "./viagens/arraialDoCabo.png";
import tokyo from "./viagens/tokyo.png";
import recife from "./viagens/recife.png";
import cusco from "./viagens/cusco.png";
import sidney from "./viagens/sidney.png";
import bangkok from "./viagens/bangkok.png";
import paris from "./viagens/paris.png";
import amsterda from "./viagens/amsterda.png";
import cidadeDoMexico from "./viagens/cidadeDoMexico.png";
import madrid from "./viagens/madrid.png";
import losAngeles from "./viagens/losAngeles.png";
import lisboa from "./viagens/lisboa.png";

import uuid from "react-native-uuid";
import { User } from "../src/types/user";
import { TripTypes, Trip } from "../src/types/trip";

const server: { usuarios: User[]; viagens: Trip[] } = {
  usuarios: [
    {
      id: uuid.v4(),
      name: "Luiz Fernando",
      birthDate: "01/01/2020",
      cpf: "111.222.333-44",
      gender: "Masculino",
      phone: "010203040",
      city: "Belo Horizonte",
      state: "Minas Gerais",
      email: "luiz@gmail.com",
      password: "123",
    },
  ],
  viagens: [
    {
      title: "Atravesse o Deserto no Chile",
      value: 3769,
      photo: atacama,
      dateDeparture: "23/09/2025",
      dateReturn: "30/09/2025",
      origin: "Rio Branco",
      stateOrigin: "Acre",
      destination: "Atacama",
      type: TripTypes.ONE_WAY,
    },
    {
      title: "Navegue pelos canais de Veneza",
      value: 4638.9,
      photo: veneza,
      dateDeparture: "13/07/2025",
      dateReturn: "23/07/2025",
      origin: "Maceió",
      stateOrigin: "Alagoas",
      destination: "Veneza",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Conheça a Terra do Fogo",
      value: 5769.5,
      photo: patagonia,
      dateDeparture: "03/04/2025",
      dateReturn: "13/04/2025",
      origin: "Fortaleza",
      stateOrigin: "Ceará",
      destination: "Patagonia",
      type: TripTypes.ONE_WAY,
    },
    {
      title: "Aprecie milhões de anos de história geológica",
      value: 5837.53,
      photo: grandCanyon,
      dateDeparture: "06/08/2025",
      dateReturn: "26/08/2025",
      origin: "Cuiabá",
      stateOrigin: "Mato Grosso",
      destination: "Grand Canyon",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Conheça a Turquia",
      value: 1000,
      photo: turquia,
      dateDeparture: "09/09/2024",
      dateReturn: "12/09/2024",
      origin: "Belo Horizonte",
      stateOrigin: "Minas Gerais",
      destination: "Turquia",
      type: TripTypes.ONE_WAY,
    },
    {
      title: "Visite a impressionante Cordilheira dos Andes",
      value: 2946,
      photo: cordilheiraDosAndes,
      dateDeparture: "19/11/2025",
      dateReturn: "04/12/2025",
      origin: "Palmas",
      stateOrigin: "Tocantins",
      destination: "La paz",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "1 semana em Nova York",
      value: 1550,
      photo: novaYork,
      dateDeparture: "12/06/2023",
      dateReturn: "19/06/2023",
      origin: "Rio de Janeiro",
      stateOrigin: "Rio de Janeiro",
      destination: "Nova York",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Conheça bonito",
      value: 580,
      photo: bonito,
      dateDeparture: "14/12/2023",
      dateReturn: "17/12/2023",
      origin: "São Paulo",
      stateOrigin: "São Paulo",
      destination: "Bonito",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Vá para Toronto",
      value: 900,
      photo: toronto,
      dateDeparture: "01/02/2024",
      origin: "São Paulo",
      stateOrigin: "São Paulo",
      destination: "Toronto",
      type: TripTypes.ONE_WAY,
    },
    {
      title: "Uma viagem inesquecível",
      value: 5590,
      photo: viena,
      dateDeparture: "05/03/2024",
      dateReturn: "10/03/2024",
      origin: "Recife",
      stateOrigin: "Pernambuco",
      destination: "Viena",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Um encontro com o Brasil",
      value: 850,
      photo: salvador,
      dateDeparture: "07/09/2024",
      dateReturn: "17/09/2024",
      origin: "Florianópolis",
      stateOrigin: "Santa Catarina",
      destination: "Salvador",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Maldivas brasileiras",
      value: 999,
      photo: arraialDoCabo,
      dateDeparture: "23/08/2024",
      dateReturn: "23/09/2024",
      origin: "Manaus",
      stateOrigin: "Amazonas",
      destination: "Arraial do Cabo",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "3 noites em Tokyo",
      value: 1207,
      photo: tokyo,
      dateDeparture: "23/08/2024",
      dateReturn: "26/08/2024",
      origin: "Vitória",
      stateOrigin: "Espírito Santo",
      destination: "Tokyo",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Aproveite seu verão em grande estilo",
      value: 2890,
      photo: recife,
      dateDeparture: "25/11/2024",
      dateReturn: "10/12/2024",
      origin: "Florianópolis",
      stateOrigin: "Santa Catarina",
      destination: "Recife",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Conheça Cusco",
      value: 3940,
      photo: cusco,
      dateDeparture: "10/01/2025",
      dateReturn: "20/01/2025",
      origin: "Belo Horizonte",
      stateOrigin: "Minas Gerais",
      destination: "Cusco",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Estude na Austrália",
      value: 6020,
      photo: sidney,
      dateDeparture: "25/02/2025",
      origin: "Goiânia",
      stateOrigin: "Goiás",
      destination: "Sidney",
      type: TripTypes.ONE_WAY,
    },
    {
      title: "Uma semana incrível",
      value: 9370,
      photo: bangkok,
      dateDeparture: "18/03/2025",
      dateReturn: "25/03/2025",
      origin: "São Luis",
      stateOrigin: "Maranhão",
      destination: "Bangkok",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Visite a cidade luz",
      value: 12356,
      photo: paris,
      dateDeparture: "05/04/2025",
      dateReturn: "30/04/2025",
      origin: "Brasília",
      stateOrigin: "Distrito Federal",
      destination: "Paris",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "5 dias em Amsterdã",
      value: 5700,
      photo: amsterda,
      dateDeparture: "02/05/2025",
      dateReturn: "07/05/2025",
      origin: "Maceió",
      stateOrigin: "Alagoas",
      destination: "Amsterdã",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "México como você nunca viu",
      value: 2460,
      photo: cidadeDoMexico,
      dateDeparture: "14/05/2025",
      dateReturn: "24/05/2025",
      origin: "Belém",
      stateOrigin: "Pará",
      destination: "Cidade do México",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Viva a noite de Madrid",
      value: 1900,
      photo: madrid,
      dateDeparture: "10/06/2025",
      dateReturn: "20/06/2025",
      origin: "Porto Alegre",
      stateOrigin: "Rio Grande do Sul",
      destination: "Madrid",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "O melhor de Los Angeles",
      value: 10850,
      photo: losAngeles,
      dateDeparture: "25/07/2025",
      dateReturn: "30/07/2025",
      origin: "Palmas",
      stateOrigin: "Tocantins",
      destination: "Los Angeles",
      type: TripTypes.ROUND_TRIP,
    },
    {
      title: "Passeie pela capital portuguesa",
      value: 2397,
      photo: lisboa,
      dateDeparture: "14/08/2025",
      dateReturn: "24/08/2025",
      origin: "Teresina",
      stateOrigin: "Piauí",
      destination: "Lisboa",
      type: TripTypes.ROUND_TRIP,
    },
  ],
};

export default server;
